// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs1w6L6-cFNbTLNH1UTgi6rAxtvwH6VWw',
    appId: '1:1071893055653:web:3d0623359d189a04cde54c',
    messagingSenderId: '1071893055653',
    projectId: 'asistencia-vehicular-bd3a4',
    authDomain: 'asistencia-vehicular-bd3a4.firebaseapp.com',
    storageBucket: 'asistencia-vehicular-bd3a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8DLrcrZjr4bwCUQpm3qksS4m3tnfrB54',
    appId: '1:1071893055653:android:d4f5d624f97b26b2cde54c',
    messagingSenderId: '1071893055653',
    projectId: 'asistencia-vehicular-bd3a4',
    storageBucket: 'asistencia-vehicular-bd3a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ziKcVuLYxaDBLBHWOKWj2N2eXzoulhE',
    appId: '1:1071893055653:ios:12b1771c40bbf15fcde54c',
    messagingSenderId: '1071893055653',
    projectId: 'asistencia-vehicular-bd3a4',
    storageBucket: 'asistencia-vehicular-bd3a4.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ziKcVuLYxaDBLBHWOKWj2N2eXzoulhE',
    appId: '1:1071893055653:ios:12b1771c40bbf15fcde54c',
    messagingSenderId: '1071893055653',
    projectId: 'asistencia-vehicular-bd3a4',
    storageBucket: 'asistencia-vehicular-bd3a4.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs1w6L6-cFNbTLNH1UTgi6rAxtvwH6VWw',
    appId: '1:1071893055653:web:6bb1a3780695902acde54c',
    messagingSenderId: '1071893055653',
    projectId: 'asistencia-vehicular-bd3a4',
    authDomain: 'asistencia-vehicular-bd3a4.firebaseapp.com',
    storageBucket: 'asistencia-vehicular-bd3a4.firebasestorage.app',
  );
}
